parameters:

  app_name: "He!p-Desk"
  full_app_name: "He!p-Desk"
  no_reply: "no-reply@example.com"

  webmasterName: "Webmaster"
  webmasterEmail: "webmaster@example.com"
  phoneNumber: '(+49) 0123/456-0000'
  infoEmail: 'info@example.com'
  legalEmail: 'legal@example.com'
  addressStreet: 'Paul-Gerhardt-Str. 7'
  addressPlz: '123456'
  addressCity: 'Ludwigsburg'
  addressCountry: 'Deutschland'

  generalManager: "Ronijan"
  taxNumber: "DE000000000"

  app_version: "3.1.14"
  
  app_author: "Khalilleo Teams"
  app_created: "2024-07-01"
  app_made_by: "khalilleo.com"

  attachments: '%kernel.project_dir%/public/uploads/attachment'

  # API
  api_user_agent: "Demo-Helpdesk-App"
  api_key: "nnf407n1-en62-42n9-bn97-36fn367ncf9n"